CREATE TABLE llx_lemonsuperpdp_reception (
  rowid              integer AUTO_INCREMENT PRIMARY KEY,
  entity             integer NOT NULL DEFAULT 1,
  superpdp_id        bigint NULL,
  source             varchar(16) NOT NULL DEFAULT 'pa',
  fk_facture_fourn   integer NULL,
  fk_soc             integer NULL,
  supplier_name      varchar(255) NULL,
  supplier_siren     varchar(20) NULL,
  supplier_vat       varchar(32) NULL,
  invoice_number     varchar(64) NULL,
  invoice_type_code  varchar(8) NULL,
  invoice_date       date NULL,
  due_date           date NULL,
  total_ht           double(24,8) NULL,
  total_ttc          double(24,8) NULL,
  currency_code      varchar(8) NULL,
  status             varchar(32) NOT NULL DEFAULT 'new',
  lifecycle_status   varchar(16) NULL,
  error_message      text NULL,
  payload_raw        mediumtext NULL,
  date_fetched       datetime NOT NULL,
  date_imported      datetime NULL,
  tms                timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_import     integer NULL
) ENGINE=innodb;
